### ISSUE TITLE
ToDo for Manager 2.0

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#973]
- [ ] Make Manager protected for big installations (e.g. hotel), like having an admin settable password in the hidden.php
- [ ] Templates for hidden.php section settings (a bit like the XSD for the config) to give the admin hints about the valid keys
- [ ] Icons should show all available icons (not only the SVG ones) and also show different sizes and colors of a selected one

**Comment by ChristianMayer** [comment]
- [ ] strictly enforce the file system structure:
  - /config/ - contains only config files (i.e. file format `visu_config.xml` and `visu_config_*.xml`) and the `hidden.php`
  - /config/media/ - can contain any file and subfolders, no restrictions
  - /config/backup/ - automatic backup files of config files, file name `visu_config*-DATECODE.xml`

  Any files/folders that don't follow should not be displayed in the normal mode. The expert mode might show them but the only possible interaction should be "passive" (i.e. download and perhaps read only text editor)

**Comment by peuter** [comment]
What abount Config-Include files in this structure, are they allowed in the `config/` Folder?

**Comment by ChristianMayer** [comment]
As of today "snippets" (files to be included in a config file) would only be allowed in the `config/media/` folder as those (usually) don't fit to the file name structure and definitely don't fit the syntax of a normal config (e.g. as they must not contain a `<pages></pages>` element).

But I'm open to relax that requirement a bit when we would force a strict file name structure for them like `visu_snipplet_*.xml`.

The idea behind being strict here is two fold:

1. A strict structure helps the user to make good decisions about where to put what content (avoid "Qual der Wahl")
1. A strict structure also helps us to have a simple infrastructure for automated tasks, like backups.

**Comment by ChristianMayer** [comment]
For the first point: see also #1090

**Comment by ChristianMayer** [comment]
Moved to a later milestone as the current level of the editor is IMHO fine for 0.12.0
